# Generated by Django 2.2 on 2019-12-06 20:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_plate_number', models.CharField(max_length=128)),
                ('sold_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.CharField(blank=True, max_length=256)),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='myald.Car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='myald.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_priority', models.BooleanField()),
                ('address', models.CharField(max_length=256)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dealers', to='myald.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdersJobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=512)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('date_expected', models.DateTimeField(null=True)),
                ('part_of_day_expected', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1)),
                ('is_auto_sending', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(null=True)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='myald.City')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='myald.Client')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='myald.Contract')),
                ('dealer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myald.Dealer')),
                ('order_job_types', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myald.OrdersJobType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('maintaince_kms', models.IntegerField()),
                ('maintaince_years', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='myald.Car')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order_job_types', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myald.OrdersJobType')),
            ],
        ),
        migrations.CreateModel(
            name='JobsDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mileage', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('jobs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myald.Car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myald.Client')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myald.Dealer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DealersModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='myald.Dealer')),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='myald.Model')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
