# Generated by Django 2.2 on 2019-12-06 20:46

from django.db import migrations


def create_valentin(apps, schema_editor):
    from django.contrib.auth.models import User

    superuser = User.objects.create_superuser(
        username='valentin',
        email='valentin@ostrovok.ru',
        password='123'
    )

    superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_valentin),
    ]
