# Generated by Django 2.2 on 2019-12-06 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0002_auto_20191206_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myald.Model'),
            preserve_default=False,
        ),
    ]
