# Generated by Django 2.2 on 2019-12-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0004_auto_20191206_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='last_service_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='last_service_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='next_service_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='next_service_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
