# Generated by Django 2.2 on 2019-12-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0005_auto_20191206_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='logo',
            field=models.CharField(default='321', max_length=256),
            preserve_default=False,
        ),
    ]
