# Generated by Django 2.2 on 2019-12-06 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0006_model_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtype',
            name='order_job_types',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_job_types',
        ),
        migrations.AddField(
            model_name='jobtype',
            name='is_main_service',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersjobtype',
            name='job_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='myald.JobType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersjobtype',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='myald.Order'),
            preserve_default=False,
        ),
    ]
