# Generated by Django 2.2 on 2019-12-06 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0007_auto_20191206_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealersmodels',
            name='dealer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dealers_models', to='myald.Dealer'),
        ),
    ]
