# Generated by Django 2.2 on 2019-12-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0009_auto_20191206_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='name',
            field=models.CharField(default='Valentin', max_length=256),
            preserve_default=False,
        ),
    ]
