# Generated by Django 2.2 on 2019-12-06 23:50

from django.db import migrations
class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0010_dealer_name'),
    ]

    operations = [
    ]
