# Generated by Django 2.2 on 2019-12-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0011_auto_20191206_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('in progress', 'in progress'), ('sent', 'sent')], default='created', max_length=32),
            preserve_default=False,
        ),
    ]
