# Generated by Django 2.2 on 2019-12-07 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0012_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersjobtype',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='myald.Order'),
        ),
    ]
