# Generated by Django 2.2 on 2019-12-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0013_auto_20191207_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsdone',
            name='contract',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myald.Contract'),
            preserve_default=False,
        ),
    ]
