# Generated by Django 2.2 on 2019-12-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0015_auto_20191207_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='email',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='lattitude',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dealer',
            name='longtitude',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
