# Generated by Django 2.2 on 2019-12-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0016_auto_20191207_1422'),
    ]

    operations = [
    ]
