# Generated by Django 2.2 on 2019-12-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0017_auto_20191207_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsdone',
            name='jobs',
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(default='321', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='test', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='test', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='test', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='7899911', max_length=32),
            preserve_default=False,
        ),
    ]
