# Generated by Django 2.2 on 2019-12-07 16:18

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0018_auto_20191207_1616'),
    ]

    operations = [
    ]
