# Generated by Django 2.2 on 2019-12-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0020_auto_20191207_1622'),
    ]

    operations = [
    ]
