# Generated by Django 2.2 on 2019-12-07 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0022_auto_20191207_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealersmodels',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dealers_models', to='myald.Dealer'),
        ),
        migrations.AlterField(
            model_name='dealersmodels',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myald.Model'),
        ),
    ]
