# Generated by Django 2.2 on 2019-12-07 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0023_auto_20191207_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myald.City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myald.Client'),
        ),
    ]
