# Generated by Django 2.2 on 2019-12-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0025_auto_20191207_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_number',
            field=models.CharField(default='-', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(default='-', max_length=128),
            preserve_default=False,
        ),
    ]
