# Generated by Django 2.2 on 2019-12-08 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myald', '0027_auto_20191208_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersjobtype',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myald.JobType'),
        ),
        migrations.AlterField(
            model_name='ordersjobtype',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='myald.Order'),
        ),
    ]
