version: '3.3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_hackaton
      - POSTGRES_PASSWORD=hello_hackaton
      - POSTGRES_DB=hello_hackaton_dev
  frontend:
        build: ./frontend
        volumes:
          - ./frontend:/app
          # One-way volume to use node_modules from inside image
          - /app/node_modules
        ports:
          - "3000:3000"
        environment:
          - NODE_ENV=development
        depends_on:
          - web
        command: npm start

volumes:
  postgres_data: